<?php

namespace ContainerY6Xsglu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_24T70NxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.24T70Nx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.24T70Nx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactEncoder' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'mailService' => ['privates', 'App\\Service\\MailService', 'getMailServiceService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'contactEncoder' => '?',
            'mailService' => 'App\\Service\\MailService',
            'manager' => '?',
        ]);
    }
}
