<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJshmkuV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJshmkuV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJshmkuV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJshmkuV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJshmkuV\App_KernelDevDebugContainer([
    'container.build_hash' => 'JshmkuV',
    'container.build_id' => '99f0d621',
    'container.build_time' => 1697458840,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJshmkuV');
